spring.application.name=ms-transport-tracking

server.port=${PORT:8080}
server.address=0.0.0.0

# Configuración de base de datos MySQL (Railway)
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:44318/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zHwshsyxQahOFtNxTvXECwxlTfforvdh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

